---
production:
  use_cors: false
  use_helmet: false
  port: 8080
  logFile: "./prod.log"
  loggerLevel: info
  urlMongo: sabius_alpha_db
  portMongo: 27017
  
development:
  use_cors: true
  use_helmet: true
  port: 8081
  logFile: "../../dev.log"
  loggerLevel: info
  urlMongo: localhost
  portMongo: 27017

testing:
  use_cors: true
  use_helmet: true
  port: 8081
  logFile: "../../dev.log"
  loggerLevel: info
  urlMongo: sabius:sabius@ds151528.mlab.com
  portMongo: 51528